server:
  port: 8080

spring:
  application:
    name: rabbitmq
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhengjiaxing
  redis:
    # database: 0
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10   #消费者数量
        max-concurrency: 10
        prefetch: 1   #消费者每次从队列获取的消息数量
        default-requeue-rejected: true  #消费失败，自动重新入队
    template:
      retry:
        enabled: true   #启用发送重试
        initial-interval: 1000
        max-attempts: 3
        max-interval: 1000
        multiplier: 1.0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zjx.entity

logging:
  level:
    com:
      zjx:
        mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check