server:
  port: 8080

spring:
  application:
    name: seckill
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhengjiaxing
  redis:
   # database: 0
    host: 192.168.204.128
    port: 6379
    password: zjx123    # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    #clusters: 10.10.1.1:7000,10.10.1.1:7001,10.10.1.1:7002,10.10.1.1:7003,10.10.1.1:7004,10.10.1.1:7005

logging:
  level:
    com:
      zjx:
        mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zjx.domain

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logback:
  appName: seckill-demo
  logstash:
    url: 192.168.204.128
    port: 9601