server:
  port: 8080

spring:
  application:
    name: spring-cache
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.160.128:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zjx123
  jpa:
    show-sql: true
  redis:
    database: 0
    host: 192.168.160.128
    port: 6379
    password: zjx123     # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）

  cache:
    type: redis

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace